### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by magicuniverse-azeem** [znetstar/get-aria2#1]
Getting `env: node\r: No such file or directory` when I run `./node_modules/get-aria2/bin/get-aria2 aria2 -p darwin -a x64 -c`.

Temporarily made it work by opening `./node_modules/get-aria2/bin/get-aria2` file in my IDE and replacing the line separators from WIndows (\r\n) to Unix or OS X (\n)

**Comment by znetstar** [comment]
Thanks for pointing that out! When I made a change on Windows it must have not changed the text back to LF from CRLF. I've added a ".gitattributes" file to prevent it from happening again. Should be fixed in v1.0.8.
